// Code generated by entc, DO NOT EDIT.

package predicate

import (
	"entgo.io/ent/dialect/sql"
)

// Header is the predicate function for header builders.
type Header func(*sql.Selector)

// Message is the predicate function for message builders.
type Message func(*sql.Selector)

// User is the predicate function for user builders.
type User func(*sql.Selector)
