// Code generated by entimport, DO NOT EDIT.

package schema

import (
	"entgo.io/ent"
	"entgo.io/ent/dialect/entsql"
	"entgo.io/ent/schema"
	"entgo.io/ent/schema/edge"
	"entgo.io/ent/schema/field"
)

type Message struct {
	ent.Schema
}

func (Message) Fields() []ent.Field {
	return []ent.Field{field.Int32("id"), field.Int32("header_id").Optional().Unique(), field.Bool("is_from_sender").Optional(), field.String("content").Optional(), field.Bool("read").Optional(), field.Time("sent_at").Optional()}
}
func (Message) Edges() []ent.Edge {
	return []ent.Edge{edge.From("header", Header.Type).Ref("message").Unique().Field("header_id")}
}
func (Message) Annotations() []schema.Annotation {
	return []schema.Annotation{entsql.Annotation{Table: "message"}}
}
